# -*- coding: utf-8 -*-
"""MachineLearningTasksChiSquaredFinal.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TjevX3DhGW8SOXQycBvPl4B75pWRVY9d
"""

import numpy as np 
import pandas as pd
import scipy

import seaborn as sns
from matplotlib import pyplot as plt
import random

#Adapted from https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html
#Initialising the dataframe

import pandas as pd

data = {'Collar': ['White Collar', 'Blue Collar', 'No Collar'],
        'A': [90, 30, 30],
        'B': [60, 50, 40], 
        'C': [104, 51, 45],
        'D': [95, 20, 35]
        }

df = pd.DataFrame(data)
df

#https://stackoverflow.com/questions/53414960/how-do-i-create-a-sum-row-and-sum-column-in-pandas
#Append the rows of other, producing a new object.
df.append(df.sum().rename('Total')).assign(Total=lambda d: d.sum(1))

# https://towardsdatascience.com/gentle-introduction-to-chi-square-test-for-independence-7182a7414a95
# set treatments column as index
dfchi = df.set_index('Collar')
dfchi.head()

#https://machinelearningmastery.com/chi-squared-test-for-machine-learning/
#The Pearson’s chi-squared statistical hypothesis is a test for independence between categorical variables.
#A contingency table contains a different number of observations for each population (row), but a similar proportion across each group (column).
from scipy.stats import chi2_contingency


chi2_contingency(dfchi)

#https://machinelearningmastery.com/chi-squared-test-for-machine-learning/
#The critical value is found and investigated, finding that the variables are independent (failure to reject H0). The identification of the p-value makes the same finding.
pvalue=chi2_contingency(dfchi)[1]
pvalue
