# -*- coding: utf-8 -*-
"""SDEV_versusSDEVS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gRNV5vK4OXAyrIWG4nWE-K8bn0WAs_Xj

Adapted from http://mathbitsnotebook.com/Algebra1/StatisticsData/STPopSample.html
and https://likegeeks.com/python-standard-deviation/
 
 
In assessing statistical data, it is pertinent to differentiate between
"population" data and "sample" data. A population data set incorporates all members of a certain grouping, i.e all values, or count (n). Every person living in the US is an example. A sample data set includes a part, or a part of, the population. The proportion of a sample is always less than the proportion of the population from the selection, i.e (n - 1). It can be said that this would represent some of the people living in the US.
 
 
When one is calculating standard deviation, the difference being noted between the sample and the population is paramount as for example utilising only a sample of the data may lead one to make generalisations in error regarding the full population set.
 
The standard deviation permits the measurement of how spread out numbers in a data set are and how apart from the mean value they are.
Adapted from http://mathbitsnotebook.com/Algebra1/StatisticsData/STPopSample.html
and https://likegeeks.com/python-standard-deviation/
 
 
In assessing statistical data, it is pertinent to differentiate between
"population" data and "sample" data. A population data set incorporates all members of a certain grouping, i.e all values, or count (n). Every person living in the US is an example. A sample data set includes a part, or a part of, the population. The proportion of a sample is always less than the proportion of the population from the selection, i.e (n - 1). It can be said that this would represent some of the people living in the US.
 
 
When one is calculating standard deviation, the difference being noted between the sample and the population is paramount as for example utilising only a sample of the data may lead one to make generalisations in error regarding the full population set. 
 
The standard deviation permits the measurement of how spread out numbers in a data set are and how apart from the mean value they are.

Adapted from https://stackoverflow.com/questions/34133939/is-there-any-difference-between-numpy-std-and-excel-stdev-function
STDEV estimates the population's standard deviation using the sample information, but STDEVP estimates the sample's standard deviation, which is the population's if it represents the entire population. In python3.4 the statistics module as part of the standard library. Statistics.stdev() is used for the sample standard deviation and statistics.pstdev() is used for the population standard deviation.

Adapted from https://www.exceltip.com/statistical-formulas/how-to-use-excel-stdev-p-function.html
STDEV.P function incorporates entire data, and certain points may skew the result sof the standard tandard deviation, also the standard deviation will be taken everyone in data, including minorities, this is known as Biased Analysis. This is why this standard deviation is identified to use only when an analysis is non-destructive. The STDEV.S or STDEV function is used on a reduced sample of the full population, and we subtract one from the denominator, also known as the number of samples arguments. This is known as non-biassed analysis of standard deviation. This is utilised when an analysis is destructive.

https://www.exceltip.com/statistical-formulas/how-to-use-the-stdev-function-in-excel.html
Show how to display STDEV manually in Excel and variation of STDEV.S and STDEV.P function
Excel offers two functions to calculate in standard deviation. STDEV.P and STDEV.S.

STDEV.P is used to show standard deviation, when you have chosen whole population data.

When you have a sample of the larger data, you should adopt the STDEV.S function. When adopted, it is more accurate than standard deviation of population (STDEV.P).

If you estimate standard deviation on same data, using STDEV.S and STDEV.P. The STDEV.S will produce a larger standard deviation. The standard deviation of a sample calculates probability of error and subtracts 1 denominator or number of observations. This is known as Bessel’s Correction.
"""

#https://stackoverflow.com/questions/34133939/is-there-any-difference-between-numpy-std-and-excel-stdev-function
# Excel's STDEV estimates the sample standard deviation, however, NumPy's std estimates the population standard deviation by default, it operates like Excel's STDEVP). In order for NumPy's std function to act like Excel's STDEV, pass in the value ddof=1:
# The following is an example of STDEV.S function
import numpy 
numpy.std([5,4,3,2,1], ddof=1)
#This enumerates the standard deviation, by utilising the sample variance whereby one divides by n-1 rather than n.

#NumPy's std estimates the population standard deviation by default dividing by n
import numpy
numpy.std([5,4,3,2,1])

#Adapted from https://stackoverflow.com/questions/64884294/stdev-s-and-stdev-p-using-numpy

#use the below to calculate the standard deviation of the sample

x = ([4, 4, 6, 7, 8, 9, 3, 4, 5, 6, 7, 8, 9])
numpy.array(x).std(ddof=1)

#use the below to calculate the standard deviation of the sample

numpy.sqrt(numpy.sum((x - numpy.mean(x))**2)/(len(x)-1))

#Adapted from https://stackoverflow.com/questions/64884294/stdev-s-and-stdev-p-using-numpy

#use the below to calculate the standard deviation of a population


numpy.array(x).std


3.060788

numpy.sqrt(numpy.sum((x - numpy.mean(x))**2)/(len(x)))